Analisando

In [39]:
import pandas as pd
import numpy as np
import io
from google.colab import files

In [10]:
file_uploaded = files.upload()

Saving AB_NYC_2019.csv to AB_NYC_2019.csv

In [12]:
df = pd.read_csv( io.BytesIO( file_uploaded['AB_NYC_2019.csv'] ) )

In [25]:
display(df.head())

# comandos para inspecinar a tabela
# 1 Descobrir o tipo da variável 
type(df)

# Numero de linhas e colunas da tabela
df.shape

# 3. Mostrar as primeiras linhas da tabela
df.head()

# 4. Descobriri os tipos de dados das colunas
df.dtypes

# 5. Numero de dados faltantes da planilha
df.isna().sum()

# 6. Informações gerais sobre a planilha
df.info()

# 7. selecionar colunas 
colunas = ['host_name', 'price']

# df.loc[linhas, colunas]

#df.loc[:, colunas]

consulta1 = df.loc[:, ['host_name', 'price']]

consulta1.head()

# 8.

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

**Consultas em colunas**

In [31]:
colunas = ['host_name', 'price']

# df.loc[linhas, colunas]

#df.loc[:, colunas]

consulta1 = df.loc[:, ['host_name', 'price']]

consulta1.head()

     host_name  price
0         John    149
1     Jennifer    225
2    Elisabeth    150
3  LisaRoxanne     89
4        Laura     80

In [36]:
consulta1 = df.dropna()

In [38]:
consulta1.shape

(38821, 16)

Respondendo as perguntas do CEO

1 - média dos aluguéis da cidade = $ 142,33

In [41]:
preco = ['price']

media = consulta1.loc[:, preco]
np.mean(media)

price    142.332526
dtype: float64


2 - nome das regiões de NY = 'Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island

In [44]:
regiao = ['neighbourhood_group']

bairros = consulta1.loc[:, regiao]

np.unique(bairros)

array(['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island'],
      dtype=object)

3 - Valor de aluguel mais caro da cidade = $10000

In [45]:
aluguel = ['price']

preco = consulta1.loc[:, aluguel]

np.max(preco)

price    10000
dtype: int64